### ISSUE TITLE
ARM & Thum mixed instruction set mod

### ISSUE THREAD

**Issue by pabx06** [threatrack/ghidra-fid-generator#2]
hello. great project. 

i am trying to fid some mixed mode binary  i loaded the project as thumb languageID. 

And ghidra function fid wont allow only same languageID do i cant not use both ARM mode and thumb mode FIDDB. only thumb FIDDB.

i could not find a workaround so far.

**Comment by 0x6d696368** [comment]
This is an interesting question.
Unfortunately, as far as I know Function ID databases can only have one language ID and they are also loaded based on the binaries language ID.
I would recommend (if not already done) to raise this question in the NSA Ghidra repository, maybe someone there can help.
